config/routes.rb
Rails.application.routes.draw do
  devise_for :players, :controllers =>  {:registrations => 'players/registrations', :omniauth_callbacks => "players/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #Static Routes
  root to: "welcome#home"
  get '/about' => "welcome#about"

  #Routes for Game Controller
  resources :games, only: [:index, :show, :new, :create] do
    resources :locations, only: [:show, :index, :edit, :update]
  end
  get '/games/:id/join' => "games#join", as: '/join'
  post '/games/:id/start' => "games#start", as: '/start'
  get '/games/:id/status' => "games#status", as: '/status'
  get '/games/:id/setup' => "games#generate_locations", as: '/setup'
  get '/mygames' => "games#my_games", as: '/mygames'
  #Routes for Characters
  resources :players, only: [:show, :edit, :update] do
    resources :characters, except: :destroy
  end

end

app/models/game.rb
class Game < ApplicationRecord
  has_many :locations
  has_many :ordered_locations
  has_many :game_players
  has_many :players, through: :game_players
  has_many :game_characters
  has_many :characters, through: :game_characters

  validates :title, presence: true
  validates :map_size, numericality: {only_integer: true}, inclusion: {in: (4..20)}

  def self.pending_games
    Game.where(status: "pending").order(:id)
  end

  def self.my_games(player)
    self.joins(:players).where("players.id = ?", player.id)
  end

  def no_more_characters?(player)
    self.class.joins(:characters).where('characters.player_id = ? AND game_characters.game_id = ?', player.id, self.id).size >= 2
  end

  def joinable?
    self.status == "pending"
  end

  def launchable?
    self.players.size > 1 && self.status == "pending"
  end

  def whose_turn_is_it_anyway
    theirs = self.players.detect{|player| player.id == self.turn}
    theirs.alias unless theirs.nil?
  end

  def switch_turn
    next_player = self.players.detect {|player| player.id != self.turn }  ##note: currently works only with 2-player game
    self.update(turn: next_player.id)
  end

  def game_over?
    self.players.collect {|player| self.locations.all?{|location| location.controlled_by == player.id}}.any?
  end

  def winner_id
    self.locations.first.controlled_by if game_over?
  end

  def no_locations?
    self.locations.empty?
  end

  def assign_locations(player_array)  ##works only for 2-players atm
    if player_array.size == 1
      self.map_size.times do
        location = Location.create(game_id: self.id, controlled_by: player_array[0].id, content: Faker::ChuckNorris.fact, defense: rand(50..200))
      end
    else
      i = 0
      until i >= self.map_size/2
        self.locations[i].update(controlled_by: player_array[1].id, content: Faker::StarWars.quote, defense: rand(50..200))
        i += 1
      end
    end
  end

  def configure_characters
    start_with = self.map_size/2 * 500
    self.game_characters.each{|character| character.update(troops: start_with * character.character.level)}
  end


end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_player!
  before_action :choose_game, only: [:join, :show, :start, :status, :generate_locations]

  def new
    @game = Game.new
    render layout: false
  end

  def create
    @game = Game.create(game_params)
    if @game.errors.empty?
      GamePlayer.create(player_id: current_player.id, game_id: @game.id, creator: true)
      current_player.current_game = @game
      generate_locations
      render json: @game
      # redirect_to new_player_character_path(current_player)
    else
      # flash[:error] = "Game creation failed."   ##doesn't work with json :(
      render json: @game.errors, status: 422
    end
  end

  def index
    @games = Game.all
    render json: @games
  end

  ###This is not used atm
  def my_games
    @games = Game.my_games(current_player)
    # flash[:notice] = "You don't have any games yet" if @games.empty?
    render json: @games
  end

  def show
    current_player.current_game = @game
    render json: @game
  end

  def generate_locations
    @game.assign_locations([current_player])
  end

  def join
    GamePlayer.create(player_id: current_player.id, game_id: @game.id, creator: false)
    current_player.current_game = @game
    render json: @game
  end

  def start
    turn = @game.players.sample.id  #randomly choose first player
    @game.update(status: params[:status], turn: turn)
    @game.assign_locations(@game.players)
    @game.configure_characters
    render json: @game
  end


  def status
    if @game.game_over?
      @game.update(status: "finished", winner: @game.winner_id, turn: nil)
    end
    render json: @game
  end

  private
    def choose_game
      !params[:game_id].nil? ? @game = Game.find(params[:game_id]) : @game = Game.find(params[:id])
    end

    def game_params
      params.require(:game).permit(:title, :status, :map_size, :map_name, :winner, :background_image_link)
    end
end

app/views/games/_game.html.erb
<%= link_to game.title, game_path(game) %> <br>

app/views/games/index.html.erb
<%= render partial: "games/game", collection: @games %>

app/views/games/new.html.erb
<p>
  <%= form_for @game do |f|%>

    <p>
      <strong>Create a New Game</strong>
    </p><p>
    <%= f.label "Your Game Title: " %> <br>
    <%= f.text_field :title, placeholder: @game.errors.full_messages_for(:title).first || "" , class: "field_with_errors"%> <br>
    </p><p>
    <%= f.label "Enter map size (between 4 and 20): " %> <br>
    <%= f.text_field :map_size, placeholder: @game.errors.full_messages_for(:map_size).first || "" , class: "field_with_errors"%> <br>
    </p><p>
    <%= f.label "Custom map name: " %> <br>
    <%= f.text_field :map_name, placeholder: "Default: 'Endless Swamp'" %> <br>
    </p><p>
    <%= f.label "Background Image Url (optional): " %> <br>
    <%= f.text_field :background_image_link %> <br>
    </p>
    <%= f.submit "Create" %>
  <% end %>
</p>

app/views/games/show.html.erb
<h1>Game Home Page</h1>

<%= @game.title %> <br>

<p>
  <%= (link_to "Show Locations", game_locations_path(@game)) if !@game.locations.empty? %>
  <%= (link_to "Create Locations", setup_path(@game) ) if @game.locations.empty? %>
</p>


<p>
  <%= (link_to "Join This Game", join_path(@game)) if game_joinable?%>
</p>


<p>
  <%= (button_to "Launch Game", {controller: :games, action: "start"}, method: :post, params: {id: @game.id, status: "active"}) if @game.launchable? %>
</p>