config/routes.rb
Rails.application.routes.draw do
  devise_for :players, :controllers =>  {:registrations => 'players/registrations', :omniauth_callbacks => "players/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #Static Routes
  root to: "welcome#home"
  get '/about' => "welcome#about"

  #Routes for Game Controller
  resources :games, only: [:index, :show, :new, :create] do
    resources :locations, only: [:show, :index, :edit, :update]
  end
  get '/games/:id/join' => "games#join", as: '/join'
  post '/games/:id/start' => "games#start", as: '/start'
  get '/games/:id/status' => "games#status", as: '/status'
  get '/games/:id/setup' => "games#generate_locations", as: '/setup'
  get '/mygames' => "games#my_games", as: '/mygames'
  #Routes for Characters
  resources :players, only: [:show, :edit, :update] do
    resources :characters, except: :destroy
  end

end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :player
  
  has_many :character_locations
  has_many :locations, through: :character_locations
  has_many :game_characters
  has_many :games, through: :game_characters

  enum role: [:elite, :loose_cannon]
  accepts_nested_attributes_for :game_characters

  validates :name, presence: true
  validate :unique_for_this_player, if: :player_id


  def game_characters_attributes=(game_character_attributes)
    game_character_attributes.values.each do |gc_attrib|
      default_troops = 1000  #this will be decided by game size
      gc_attrib[:character_id].each_with_index do |char, i|
        GameCharacter.find_or_create_by(game_id: gc_attrib[:game_id], character_id: gc_attrib[:character_id][i], troops: default_troops) unless i == 0
      end
    end
  end

  def self.who_am_i(id)
    Character.find(id).name
  end

  def self.active_characters(game, player)
     self.joins(:games, :player).where("games.id = ? AND players.id = ?", game.id, player.id)
  end

  ###Variable character levels are not supported atm, but this is set ready for that
  def attack(troops)
    troops + self.level * troops
  end

  ###Custom validation
  def unique_for_this_player
    if !self.player.characters.empty?
      if self.player.characters.detect {|character| character.name == self.name}
        errors.add(:name, "not unique. All your character names need to be unique.")
      end
    end
  end


end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_player
  before_action :authenticate_player!

  def new
    @character = Character.new
    render layout: false
  end

  def create
    if assign_only?
      new_hash = character_params.delete_if{|key, value| key != "game_characters_attributes"}
      character = Character.create(new_hash)
      render json: character
    else
      @character = Character.create(character_params)
      if @character.errors.empty?
        @character.game_characters.create(game_id: current_game.id, character_id: @character.id) if current_game
        render json: @character
      else
        # flash[:error] = "Character creation failed. #{@character.errors.full_messages_for(:name).first}"
        render json: @character.errors, status: 422
      end
    end
  end

  def edit
  end

  def update
  end

  def show
    @character = Character.find(params[:id])
    render json: @character
  end

  def index
    ##only shows the characters for the current player atm
    @characters = @player.characters
    render json: @characters
  end


  private
    def character_params
      params.require(:character)
      .permit(:name, :player_id, :role, :image_link, :personality, :game_characters_attributes => [:game_id, :character_id => []])
    end

    def set_player
      @player = current_player
    end

    def assign_only?
      if character_params[:game_characters_attributes]
        character_params[:name] == "" && character_params[:game_characters_attributes]["0"][:character_id].last != ""
      end
    end

end

app/views/characters/_character.html.erb
<%= link_to character.name, player_character_path(current_player, character) %>
<%=  print_character_status(current_game.id, character.id) if current_game %> <br>

app/views/characters/index.html.erb
Characters found: <br>

<p>
<%= render partial: "characters/character", collection: @characters %>
</p>

<%= link_to "Add character", new_player_character_path(current_player) %><br>

app/views/characters/new.html.erb
<%= no_more? %>

<%= form_for [@player, @character] do |f| %>
  <%= f.label "Name Your Character: " %><br>
  <%= f.text_field :name, placeholder: @character.errors.full_messages_for(:name).first || "" , class: "field_with_errors" %><br>
  <%= f.hidden_field :player_id, value: @current_player.id %>

  <%= f.label "Provide Image URL (optional): " %><br>
  <%= f.text_field :image_link %> <br>

  <%= f.label "Personality type (optional): " %><br>
  <%= f.text_field :personality %> <br>

  <% if !can_be_added?(current_player) %>
    <%= f.submit "Create character" %>
  <% else %>
    <% if has_characters? %>
      Choose from existing characters: <br>
      <!-- choice will be limited to only two when frontend jQuery will be implemented-->
      <%= f.fields_for :game_characters, @character.game_characters.build do |game_characters_fields| %>
        <%= game_characters_fields.collection_check_boxes :character_id, current_player.characters, :id, :name %> <br>
        <%= game_characters_fields.hidden_field :game_id, value: current_game.id %>
      <% end %>
    <% end %>
    <%= f.submit "Assign to this game" %>
  <% end %>
<% end %>

app/views/characters/show.html.erb
<h1>Character Details for <%= @character.name%>:</h1>

<%= image_tag("#{@character.image_link}", width: "250") %> <br>

<%= @character.personality %> <br>

<%=  print_character_status(current_game.id, @character.id) if current_game %> <br>