config/routes.rb
Rails.application.routes.draw do
  devise_for :players, :controllers =>  {:registrations => 'players/registrations', :omniauth_callbacks => "players/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #Static Routes
  root to: "welcome#home"
  get '/about' => "welcome#about"

  #Routes for Game Controller
  resources :games, only: [:index, :show, :new, :create] do
    resources :locations, only: [:show, :index, :edit, :update]
  end
  get '/games/:id/join' => "games#join", as: '/join'
  post '/games/:id/start' => "games#start", as: '/start'
  get '/games/:id/status' => "games#status", as: '/status'
  get '/games/:id/setup' => "games#generate_locations", as: '/setup'
  get '/mygames' => "games#my_games", as: '/mygames'
  #Routes for Characters
  resources :players, only: [:show, :edit, :update] do
    resources :characters, except: :destroy
  end

end

app/views/layouts/_messages.html.erb
<!-- This file needs to be replaced by errors.html.erb OR errors.js  -->


<!-- <p>
  <% if flash[:error] %>
    <%= image_tag("http://img-cache.cdn.gaiaonline.com/ca65c057a6a1ff00665c7fe6b0379302/http://i618.photobucket.com/albums/tt266/goku14139268520/doublefacepalm.jpg", width: 250) %>
    <%= content_tag(:div, flash[:error], :id => "flash_error") %>
  <% end %>
  <% if flash[:notice] %>
    <%= image_tag("http://37.media.tumblr.com/7a01fad56d40a67d366fb58cabe71f77/tumblr_mq4z97dX0h1s9ctlvo1_500.gif", width: 250) %>
    <%= content_tag(:div, flash[:notice], :id => "flash_notice") %>
  <% end %>
  <% if flash[:message] %>
    <%= image_tag("https://66.media.tumblr.com/dbe1a42d8d528f7bcf47d160ab844020/tumblr_nkljtzLVgn1ql3vujo3_500.gif", width: 250) %>
    <%= content_tag(:div, flash[:message], :id => "flash_message") %>
  <% end %>
</p> -->

app/views/layouts/_navbar.html.erb
  <div id = "nav_left" class = "flex left col-2">
    <%= link_to "Clear Screen", root_path, class: "flex m1" %>
    <%= link_to "About", about_path, class: "flex m1" %>
  </div>

  <% if !current_player %>

    <div id = "nav_right" class = "flex order-last right col-2">
      <%= link_to "Sign In", new_player_session_path, class: "flex m1" %>
      <%= link_to "Sign Up", new_player_registration_path, class: "flex m1" %>
    </div>

    <div id = "nav_center" class = "center col-8 m1">Welcome to Interception</div>

  <% else %>

    <div id = "nav_right" class = "flex order-last right col-2">
      <%= link_to "Sign Out", destroy_player_session_path,:method => :delete, class: "flex m1"  %>
    </div>

    <div id = "nav_center" class = "flex col-8">
      <%= link_to "Games", games_path, class: "flex m1" %>
      <%= link_to "New Game", new_game_path, class: "flex m1" %>
      <%= link_to "My Characters", player_characters_path(current_player), class: "flex m1" %>
      <%= link_to "New Character", new_player_character_path(current_player), class: "flex m1" %>
    </div>

  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InterceptionGameApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://npmcdn.com/basscss@8.0.1/css/basscss.min.css" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%# Makes the current_player id and alias visible to javascript when logged in: %>
    <% if current_player %>
      <%= javascript_tag do %>
        playerId = <%= current_player.id %>;
        playerAlias = "<%= current_player.alias %>";
      <% end %>
    <% end %>

  </head>

  <body>

    <div id = "navbar" class = "flex col-12 p1 border-box clearfix border rounded">
      <%= render partial: 'layouts/navbar' %>
    </div>
    <div id = "container" class = "p1 border-box clearfix border rounded">
      <div id = "status" class = "flex col-10 mx-auto p1 border-box border rounded clearfix block">
          <div id = "shortcut" class = "flex col-3 mx-auto p1 border-box border rounded"><%= page_content %></div>
          <div id = "alias" class = "flex col-3 mx-auto p1 border-box border rounded"></div>
          <div id = "turn" class = "flex col-3 mx-auto p1 border-box border rounded"></div>
      </div>

      <%= yield %>


    </div>
  </body>
</html>